using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// 쟕왦 썞첍 쎂칫 온첇콼쟍 쎂쟕핎 쫣쐍쾑 콟이쫔
/// </summary>
public class RhythmManager : MonoBehaviour
{
    public static RhythmManager Instance             // 쫣쐍쾑 첉쫔콾쫣
    {
        get { return instance; }
    }
    public string Title;                            // 쎂쟕  썵 촍점
    public AudioClip AudioClip;                     // 첞 썵 콟쟙
    public decimal CurrentTime;                     // 汰 쫚쌲
    public AudioData Data;                          // 썵 온첇콼
    public float Speed;                             // 쩁옷
    public float MusicSound;
    public float KeySound;
    public bool SceneChange;
    public JudgeStorage Judges;

    private static RhythmManager instance = null;

    private void Awake()
    {
        if (instance != null)
        {
            Destroy(gameObject);
        }
        else
        {
            instance = this;
            DontDestroyOnLoad(gameObject);
        }

        Judges = new JudgeStorage();
        Data = new AudioData();
        MusicSound = 0.5f;
        KeySound = 0.5f;
    }

    private void Update()
    {
        Judges.SetAttractive();

        if ((float)CurrentTime >= Data.Length && !SceneChange)
        {
            EndScene();
        }
        if (Input.GetKeyDown(KeyCode.F5) && SceneManager.GetActiveScene().name == "RhythmScene" && !SceneChange)
        {
            EndScene();
        }
    }

    /// <summary>
    /// 썵 온첇콼쟍 Json 퀛첊 첰천
    /// </summary>
    public void SaveData()
    {
        JsonManager<AudioData>.Save(Data, Title);
    }

    /// <summary>
    /// Json 퀛첊첉 썵 온첇콼 훵챰
    /// </summary>
    public void LoadData()
    {
        Data = new AudioData(Title);
    }

    public void Init()
    {
        LoadData();
        CurrentTime = 0;
        Judges.Init();
        SceneChange = false;
    }

    private void EndScene()
    {
        SceneChange = true;
        Constant.PizzaAttractiveness = Judges.Attractive;
        LoadScene.Instance.LoadPizzaMenu();
    }
}
